### PR TITLE
Delete extra indentation utils.ts

### PR DESCRIPTION
**Pull request by shareghzadeh**
make it more readable, extra indentation and spaces deleted

### CODE REVIEW

**Comment by Fecony** [comment]
@shareghzadeh Why would you spam PR to this repository by completely ignoring prettierrc file?

**Comment by shareghzadeh** [comment]
I'm trying to make it more readable for people who come to github and want to read the source code from github(like my self). shouldn't i do it?

**Comment by Fecony** [comment]
> I'm trying to make it more readable for people who come to github and want to read the source code from github(like my self). shouldn't i do it?

Did you ask @SaltyAom before doing anything?
Repository has prettier file, so it means it has some code style, but now you force another one. Even though it is not more readable. two spaces, with "" and semicolon doesn't look cleaner

**Comment by shareghzadeh** [comment]
OK, I'm sorry for making contribution to this repo

**Pull request closed without merging**
