### PR TITLE
Release 1.1: Theresa

### PR DESCRIPTION
**Pull request by SaltyAom**
Release name: [Grown-up's Paradise](https://youtu.be/KawV_oK6lIc)

Codename: [Theresa](https://arknights.fandom.com/wiki/Theresa)

Theresa

### CODE REVIEW

**Review by kravetsone — COMMENTED** [review]
wow! Is that what I was talking about?

**Comment by mdbetancourt** [comment]
Hello awesome work this framework is what i wanted in for backend ever, but has so many bug thing that dont works as it should, would be awesome if in this update you fix the most critical ones before adding new things and close resolved issues

#666: global schema is not working, macro should be able to modify schema and add new properties to context, resolve when returning errors with "error(code, body)" is not parsing the body object
#558 
#664
#662 
#658 and #656 
#647 
#641
#640
#630 
#621 
#606
#574 
#525 
#486 should be closed

I could help closing resolved issues, creating tests or programing some of them let me know how can i help

**Comment by kravetsone** [comment]
> Hello awesome work this framework is what i wanted in for backend ever, but has so many bug thing that dont works as it should, would be awesome if in this update you fix the most critical ones before adding new things and close resolved issues
> 
> #666: global schema is not working, macro should be able to modify schema and add new properties to context, resolve when returning errors with "error(code, body)" is not parsing the body object #558 #664 #662 #658 and #656 #647 #641 #640 #630 #621 #606 #574 #525 #486 should be closed
> 
> I could help closing resolved issues, creating tests or programing some of them let me know how can i help

I agree! We need to close most issues

**Comment by SaltyAom** [comment]
# lgtm 👍

doro walking

**Pull request merged**
