### PR TITLE
Change indentation to 2 space

### PR DESCRIPTION
**Pull request by shareghzadeh**

### CODE REVIEW

**Comment by SaltyAom** [comment]
Can you keep tabSize to 4?

I work on monitor large screen so it's kinda hard for me to read when tabSize was set to 2.

**Comment by shareghzadeh** [comment]
yes, why not

**Comment by Shyam-Chen** [comment]
Setting `"useTabs": false` is sufficient. Reading code from GitHub becomes easier when it is written in a structured and readable manner. The choice between 2 spaces or 4 spaces is a matter of personal preference, although in JavaScript/TypeScript, the common convention is to use 2 spaces.

**Comment by SaltyAom** [comment]
Since this have been stale as have a lot of breaking changes between version.

I decided to close the PR.
If you want a similar thing please open another PR with the updated version.

Thank you for your understanding.

**Pull request closed without merging**
