### PR TITLE
feat: add support for 401, 403 and 409 errors

### PR DESCRIPTION
**Pull request by l2ysho**
This PR closes https://github.com/elysiajs/elysia/issues/153

### CODE REVIEW

**Comment by yfrans** [comment]
After searching for this feature with no luck, I developed a small helper library called elysia-http-error which allow throwing HttpError messages more easily.
You can check it out in NPM registry: https://www.npmjs.com/package/elysia-http-error

This helped me a lot, for example when throwing this error from a derived method which checks jwt then returning the payload to be used later in a route, it allows using the type returned from the derived method without the need for null checking.

**Comment by l2ysho** [comment]
@yfrans looks good, but I think it is not big deal to implement it directly to elysia. Maybe some response from other contributors or code owners would be useful cc @SaltyAom

**Comment by yfrans** [comment]
I prefer throwing exception on errors instead of using status codes.
It allows better code flow because error is error and should break the response flow (again, my opinion).
Generic HttpError class is fine, but using a class with static initializers for common errors is more easy to handle.
But it is your library, we can only advice 😀

**Comment by l2ysho** [comment]
For me the same as for @yfrans, it is more clear for me to throw specific error right away
```javascript
if (!user) throw UnauthorizedError('Error message')
if (!permissions) throw ForbiddenError('Error message')
if (!alreadyExists) throw ConflictError('Error message')
if (!record) throw NotFoundError('Error message')

``` 

but it make sense to have one generic elysia error and handle it in onError handler

```javascript
if (!customCondition) {
      throw new ElysiaApiError(409, 'Error message')
}
```

So if you choose you prefer way I can update PR.

**Comment by yfrans** [comment]
@l2ysho I think using http code like "409", "401", etc. is similar to setting the res.status (without considering the advantage of throwing an exception).
That's why I added the initializers for each http status code.

**Comment by gabbrieu** [comment]
Any news here?

**Comment by zmzlois** [comment]
> For me the same as for @yfrans, it is more clear for me to throw specific error right away
> 
> ```js
> if (!user) throw UnauthorizedError('Error message')
> if (!permissions) throw ForbiddenError('Error message')
> if (!alreadyExists) throw ConflictError('Error message')
> if (!record) throw NotFoundError('Error message')
> ```
> 
> but it make sense to have one generic elysia error and handle it in onError handler
> 
> ```js
> if (!customCondition) {
>       throw new ElysiaApiError(409, 'Error message')
> }
> ```
> 
> So if you choose you prefer way I can update PR.

The time for a js/ts framework to have match case. Will Elysia be the first?

**Comment by SaltyAom** [comment]
#284 introduces `error` function to return a custom error without using `set`.

This function provides type inference for use later with Eden.

With the same intent functionality, I'm closing this PR.

**Pull request closed without merging**
